Repository datarobot/batch-scoring, pull requests merged in 2019-08, with the labels that each got.

#164 PRED-2832: Batch scoring with prediction explanations produces rows with varying column lengths
  datarobot_batch_scoring/__init__.py
  datarobot_batch_scoring/api_response_handlers/pred_api_v10.py
  datarobot_batch_scoring/batch_scoring.py
  datarobot_batch_scoring/writer.py
  tests/fixtures/10kDiabetes_mixed_explanations.csv
  tests/fixtures/10kDiabetes_mixed_explanations.json
  tests/liveserver_fixtures.py
  tests/test_functional.py
  tests/test_writer.py
Labels: 00 - Ready for Review, 01 - Close Jira on Merge

#165 [PRED-2860] Bump up flask version
  requirements-test.txt
Labels: Auto Merge on Green

#160 Fix a typo: CVS -> CSV
  datarobot_batch_scoring/main.py
Labels: 00 - Ready for Review

#166 PRED-2940: Clear up errors and warnings from previous runs.
  datarobot_batch_scoring/writer.py
Labels: 00 - Ready for Review

#167 Bump version to 1.16.4
  datarobot_batch_scoring/__init__.py
Labels: 00 - Ready for Review
